commands:
    install:
        description: |
            This command install aws
        steps:
            - run:
                command: |-
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip -q awscliv2.zip
                    sudo ./aws/install
                    ls
                    echo "Testing new update of orb!"
                name: Install AWS CLI v2
executors:
    default:
        description: |
            This is a sample executor base configuration.
        docker:
            - image: cimg/base:2021.10
jobs:
    hello:
        description: |
            Sample description
        executor: default
        steps:
            - install
examples:
    example:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                <orb-name>: <namespace>/<orb-name>@1.2.3
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/<job-name>

version: 2.1