commands:
    install:
        description: |
            This command install aws
        steps:
            - run:
                command: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip -q awscliv2.zip
                    sudo ./aws/install
                name: Install AWS CLI v2
executors:
    default:
        description: |
            This is a sample executor using Docker and Python.
        docker:
            - image: circleci/python:3.8
jobs:
    hello:
        description: |
            Sample description
        executor: default
        steps:
            - install
examples:
    example:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                <orb-name>: echorb/aws-install@1.0.0
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/install

version: 2.1
